### ISSUE TITLE
Pleas add Leobog Hi75

### ISSUE THREAD

**Issue by CayKhe** [NollieL/SignalRgb_CN_Key#12]
Hi SignalRgb_CN_Key 

Please creat a plug-ins for LEOBOG Hi75 

Have a good day ! 
Thanks you

**Comment by NollieL** [comment]
Added

**Comment by CayKhe** [comment]
[Sat Apr 6 21:32:34 2024] Warning - Force Reloading Plugin: Plugin: LEOBOG Hi75.js
[Sat Apr 6 21:32:34 2024] Info - Set size for device to: [21,8]
[Sat Apr 6 21:32:34 2024] Info - Loading Image...
[Sat Apr 6 21:32:34 2024] Info - Loading Image via Base64 Export function...
[Sat Apr 6 21:32:34 2024] Info - [IGNORE] endpoint.interface: 1, endpoint.usage: 0x0006, endpoint.usage_page: 0x0001, endpoint.collection: 0x0004
[Sat Apr 6 21:32:34 2024] Info - [IGNORE] endpoint.interface: 1, endpoint.usage: 0x0080, endpoint.usage_page: 0x0001, endpoint.collection: 0x0001
[Sat Apr 6 21:32:34 2024] Info - [IGNORE] endpoint.interface: 1, endpoint.usage: 0x0001, endpoint.usage_page: 0x000c, endpoint.collection: 0x0002
[Sat Apr 6 21:32:34 2024] Info - [IGNORE] endpoint.interface: 0, endpoint.usage: 0x0006, endpoint.usage_page: 0x0001, endpoint.collection: 0x0000
[Sat Apr 6 21:32:34 2024] Info - [OPEN] endpoint.interface: 1, endpoint.usage: 0x0001, endpoint.usage_page: 0xff00, endpoint.collection: 0x0003
[Sat Apr 6 21:32:34 2024] Info - [OPEN] endpoint.interface: 1, endpoint.usage: 0x0001, endpoint.usage_page: 0xff00, endpoint.collection: 0x0005
[Sat Apr 6 21:32:34 2024] Info - [OPEN] endpoint.interface: 1, endpoint.usage: 0x0001, endpoint.usage_page: 0xff00, endpoint.collection: 0x0006
[Sat Apr 6 21:32:34 2024] Info - [IGNORE] endpoint.interface: 1, endpoint.usage: 0x0002, endpoint.usage_page: 0x0001, endpoint.collection: 0x0007
[Sat Apr 6 21:32:34 2024] Info - Created Leds: 96
[Sat Apr 6 21:32:34 2024] Info - Loaded Led color overrides, count: 0

Knob button is not working
